[sdk-vpp#314] Support empty chains
networkservicemesh/sdk pull request #1044
Opened 2021-07-29 09:04 UTC by Bolodya1997

## Description
Add support for empty subchains (networkservice, NS registry, NSE registry):
```go
var serversA, serversB, serversC []networkservice.Server
...
server := chain.NewServer(
    chain.NewServer(serversA...), // <-- now can be empty
    chain.NewServer(serversB...), // <-- now can be empty
    chain.NewServer(serversC...), // <-- now can be empty
)
```

## Issue link
Need for networkservicemesh/sdk-vpp#314.

## How Has This Been Tested?

- [x] Added unit testing to cover
- [ ] Tested manually
- [ ] Tested by integration testing
- [ ] Have not tested

## Types of changes

- [x] Bug fix
- [ ] New functionallity
- [ ] Documentation
- [x] Refactoring
- [ ] CI

2021-07-30 12:12 UTC, d-uzlov approved these changes

2021-08-13 08:50 UTC, denis-tingaikin requested changes
Could you provide an example on how you plan to use this chain element in context sdk-vpp#314? Thanks.

2021-08-13 09:33 UTC, Bolodya1997 commented
@denis-tingaikin 
Removed refactoring from this PR.

2021-08-13 10:56 UTC, denis-tingaikin approved these changes

2021-08-13 10:56 UTC, merged

2021-08-13 13:29 UTC, edwarnicke commented
Why are we proliferating chain types here?

2021-08-13 13:30 UTC, edwarnicke commented
I don't follow at all why this is needed...