Return error on trying to register Network Service with same name
networkservicemesh/sdk pull request #1052
Opened 2021-08-04 09:31 UTC by Mixaster995

Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>

fixes https://github.com/networkservicemesh/sdk/issues/1048

2021-08-06 06:32 UTC, Bolodya1997 commented on pkg/registry/common/memory/ns_server.go
> +	loaded, ok := s.networkServices.Load(r.Name)
```suggestion
	loaded, ok := s.networkServices.LoadOrStore(r.Name, r.Clone())
	if ok && loaded.Payload != ns.Payload {
		return nil, errors.New("...")
	}
```

2021-08-06 08:20 UTC, Mixaster995 commented on pkg/registry/common/memory/ns_server.go
> +	loaded, ok := s.networkServices.Load(r.Name)
ok, done

2021-08-08 12:30 UTC, denis-tingaikin requested changes

2021-08-08 12:30 UTC, denis-tingaikin commented on pkg/registry/common/memory/ns_server.go
> +	}
I thought memory registry is not smart and it just replaces entries. 
I also don't quite follow why we change logic only for networkservices and don't touch networkserviceendpoints..

2021-08-10 09:41 UTC, closed without merging