Interpose should create unique name for all new interpose NSEs
networkservicemesh/sdk pull request #661
Opened 2021-01-22 03:24 UTC by Bolodya1997

# Issue
If multiple interpose NSEs will try to register with same names, we will have a collision and lose some of them.
# Solution
Generate new unique name for interpose NSEs if we haven't registered them yet before.

2021-01-22 06:17 UTC, denis-tingaikin requested changes
Please cover this by sandbox tests to make sure that it is working as expected with other applications.

2021-01-25 17:17 UTC, Bolodya1997 commented
Needs updated sandbox by #668.

2021-02-08 13:10 UTC, Bolodya1997 commented
> Please cover this by sandbox tests to make sure that it is working as expected with other applications.

Done.

2021-02-10 09:04 UTC, denis-tingaikin reviewed
Should we just add setid into interpose chain?

2021-02-10 09:24 UTC, Bolodya1997 commented
> Should we just add setid into interpose chain?

We cannot use `setid` because it would overwrite `interpose-nse#` prefix.

2021-02-10 09:55 UTC, closed without merging