Fix memory tests
networkservicemesh/sdk pull request #711
Opened 2021-02-17 07:10 UTC by Bolodya1997

# Issue
Sometimes `TestNetworkServiceEndpointRegistryServer_ShouldReceiveAllRegisters`, `TestNetworkServiceEndpointRegistryServer_ShouldReceiveAllUnregisters` fail due to the huge amount of NSEs, low timeout.
# Solution
Reduce amount, increase timeout.

2021-02-18 07:39 UTC, denis-tingaikin requested changes
These tests should be refactored.
Please pass one context with deadline to each goroutine

And do select on wg.Done() or ctx.Done()

Note: unit test should run in 1s maximum

2021-02-18 09:46 UTC, haiodo approved these changes

2021-02-18 11:51 UTC, Bolodya1997 commented
> Please pass one context with deadline to each goroutine

Done.

> And do select on wg.Done() or ctx.Done()

`sync.WaitGroup` is not a channel, we can't `select` on it. Context timeout would break `stream.Recv()` in all goroutines and so they would update `wg` - there is no need to select on `ctx.Done()`.

> Note: unit test should run in 1s maximum

Reduced to 1 second.

2021-02-18 12:47 UTC, denis-tingaikin commented
> sync.WaitGroup is not a channel, we can't select on it. Context timeout would break stream.Recv() in all goroutines and so they would update wg - there is no need to select on ctx.Done()

you could create a goroutine to wait for wg.Done.

also, can we reduce channel size and reduce find request count?

2021-02-19 06:16 UTC, haiodo approved these changes

2021-02-19 07:07 UTC, denis-tingaikin approved these changes

2021-02-19 07:07 UTC, merged