Refactor chains/memoryregistry to use Option pattern
networkservicemesh/sdk pull request #752
Opened 2021-03-05 10:12 UTC by Tiberivs

Refactor `chains/memoryregistry` to use Option pattern
Closes #735.

Signed-off-by: Anatoly Loskutnikov <anatoly.loskutnikov@gmail.com>

2021-03-05 13:35 UTC, denis-tingaikin requested changes

2021-03-05 13:35 UTC, denis-tingaikin commented on pkg/registry/chains/memory/server.go
> +func WithGRPCOptions(options ...grpc.DialOption) Option {
```suggestion
func WithDialOption(options ...grpc.DialOption) Option {
```

2021-03-05 13:35 UTC, denis-tingaikin commented on pkg/registry/chains/memory/server.go
> +}
This is a required parameter.

2021-03-05 13:35 UTC, denis-tingaikin commented on pkg/registry/core/interdomain/interdomain_ns_test.go
> +				memory.NewNetworkServiceEndpointRegistryServer())
Why?

2021-03-05 14:16 UTC, Tiberivs commented on pkg/registry/chains/memory/server.go
> +func WithGRPCOptions(options ...grpc.DialOption) Option {
Seems should be in plural.

2021-03-05 14:20 UTC, Tiberivs commented on pkg/registry/core/interdomain/interdomain_ns_test.go
> +				memory.NewNetworkServiceEndpointRegistryServer())
for best reading, why not?

2021-03-15 05:33 UTC, Tiberivs commented on pkg/registry/chains/memory/server.go
> +func WithGRPCOptions(options ...grpc.DialOption) Option {
Done

2021-03-15 05:33 UTC, Tiberivs commented on pkg/registry/chains/memory/server.go
> +}
Removed from options

2021-03-15 06:52 UTC, denis-tingaikin requested changes

2021-03-15 06:52 UTC, denis-tingaikin commented on pkg/tools/sandbox/types.go
> +type SupplyRegistryFunc func(ctx context.Context, proxyRegistryURL *url.URL, options ...memory.Option) registry.Registry
This change is critical because it can be used for testing registry-k8s or any other registry backend. So we should not use only memory.Option.

2021-04-20 05:28 UTC, denis-tingaikin commented
These changes have conflicts. We'll create a separate PR and fix all conflicts.

2021-04-20 05:28 UTC, closed without merging